concurrent = 2
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  limit = 10
  name = "Klauk eneterprises Runner 01"
  url = "https://git.klauke-enterprises.com"
  token = ""
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    Type = "s3"
    Path = "runner-cache"
    Shared = true
    [runners.cache.s3]
      ServerAddress = "minio:9000"
      AccessKey = "minio"
      SecretKey = "minio"
      BucketName = "runner"
      Insecure = true
    [runners.cache.gcs]
  [runners.docker]
    tls_verify = false
    image = "openjdk:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
